---
- name: Check if Crowdsec container exists
  community.docker.docker_container_info:
    name: crowdsec
  register: crowdsec_info

- name: Ensure Crowdsec directory exists
  ansible.builtin.file:
    path: "{{ crowdsec_folder_path }}"
    state: directory
    mode: '0777'
  when: not crowdsec_info.exists
  become: true

- name: Deploy Crowdsec acquisition file
  ansible.builtin.template:
    src: acquis.yaml.j2
    dest: "{{ crowdsec_folder_path }}/acquis.yaml"
    mode: '0644'
  when: not crowdsec_info.exists

- name: Render Crowdsec compose file
  ansible.builtin.template:
    src: crowdsec.yml.j2
    dest: /tmp/core_infrastructure/crowdsec.yml
    mode: '0644'
  when: not crowdsec_info.exists

- name: Deploy Crowdsec using Docker Compose
  community.docker.docker_compose_v2:
    project_src: /tmp/core_infrastructure
    files:
      - crowdsec.yml
  when: not crowdsec_info.exists