---
- name: Check if Pi-hole container exists
  community.docker.docker_container_info:
    name: pihole
  register: pihole_info

- name: Check if Cloudflared container exists
  community.docker.docker_container_info:
    name: cloudflared
  register: cloudflared_info

- name: Render Pi-hole plus Cloudflared compose file
  ansible.builtin.template:
    src: pihole_plus_cloudflared.yml.j2
    dest: /tmp/core_infrastructure/pihole_plus_cloudflared.yml
    mode: '0644'
  when: not pihole_info.exists and not cloudflared_info.exists

- name: Deploy Pi-hole plus Cloudflared using Docker Compose
  community.docker.docker_compose_v2:
    project_src: /tmp/core_infrastructure
    files:
      - pihole_plus_cloudflared.yml
  when: not pihole_info.exists and not cloudflared_info.exists
